# Site settings
title: Chuyik's blog
email: your-email@domain.com
description: "A place for keeping my footprints to a full-stack developer. Gonna to share something about my reflection, problem solution, tech tutorials and inspiration."
baseurl: ""
url: "http://yourdomain.com"
username: chuyik

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8

exclude: ['node_modules', 'Gemfile*', 'Guardfile', 'sass', 'gulpfile.js', 'Gruntfile.js', 'package.json', 'bower.json', 'config.rb', 'screenshot']
